import '~/alert/alert-test'
import '~/avatar/avatar-test'
import '~/color-chips/color-chips-test'
import '~/models/tests/models-test'
import '~/pdf/assemble-test'
import '~/user-avatar-picker/user-avatar-picker-test'
import '~/elements/tests/'
import '~/utils/tests/tests'
